FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    vim \
    cmake \
    git \
    wget \
    unzip \
    pkg-config \
    python3 \
    python3-pip \
    libgtk-3-dev \
    libgl1-mesa-dev \
    libglib2.0-dev \
    libopencv-dev 
  
RUN git clone https://github.com/luxonis/depthai-core.git && \
    cd depthai-core && \
    git checkout v2_stable && \
    git submodule update --init --recursive && \
    cmake -S. -Bbuild -D'BUILD_SHARED_LIBS=ON' -D'CMAKE_INSTALL_PREFIX=/opt/depthai-install' && \
    cmake --build build --target install -j4

# Install newer CMake (>= 3.24)
RUN apt-get update && \
    apt-get remove -y cmake && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN rm -rf /usr/local/bin/cmake \
           /usr/local/share/cmake* \
           /usr/local/doc/cmake* \
           /usr/local/man/man1/cmake*
RUN cd /tmp && \
    wget https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-x86_64.sh && \
    chmod +x cmake-3.27.9-linux-x86_64.sh && \
    ./cmake-3.27.9-linux-x86_64.sh --skip-license --prefix=/usr/local && \
    rm cmake-3.27.9-linux-x86_64.sh
ENV PATH="/usr/local/bin:${PATH}"
RUN cmake --version


RUN cd /tmp && wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz && \
        tar -xzf eigen-3.4.0.tar.gz && \
        cd eigen-3.4.0 && \
        mkdir build && cd build && \
        cmake .. && \
        make install && \
        cd / && rm -rf /tmp/eigen-3.4.0

RUN cd /tmp && wget https://github.com/strasdat/Sophus/archive/refs/tags/1.24.6.tar.gz && \
        tar -xzf 1.24.6.tar.gz && \
        cd Sophus-1.24.6 && \
        mkdir build && cd build && \
        cmake .. && \
        make install && \
        cd / && rm -rf /tmp/Sophus-1.24.6

RUN cd /tmp && git clone https://github.com/stevenlovegrove/Pangolin.git && \
        cd Pangolin && \
        git checkout v0.8 && \
        git submodule update --init --recursive && \
        sed -i 's/\bsudo\b//g' ./scripts/install_prerequisites.sh && \
        sed -i 's/install --no-install-suggests --no-install-recommends/install -y --no-install-suggests --no-install-recommends/g' ./scripts/install_prerequisites.sh && \
        apt-get update && \
        ./scripts/install_prerequisites.sh recommended && \
        cmake -B build && \
        cmake --build build && \
        cmake --install build && \
        rm -rf /tmp/Pangolin
RUN ldconfig


WORKDIR /workspace

CMD ["/bin/bash"]